using GenerativeAI.Gemini.Models;

namespace GenerativeAI.Gemini.Types
{
    /// <summary>
    /// Represents the response data payload returned from a Gemini API prompt.
    /// </summary>
    /// <param name="Candidates">The collection of candidate responses generated by the model.</param>
    /// <param name="UsageMetadata">Token usage statistics for the prompt and response.</param>
    /// <param name="ModelVersion">The version of the Gemini model that generated the response.</param>
    /// <param name="ResponseId">A unique identifier for this response.</param>
    internal sealed record GeminiResponseData(
        IEnumerable<Candidate> Candidates,
        GeminiUsageMetadata UsageMetadata,
        string ModelVersion,
        string ResponseId) : IGeminiResponseData;
}
