using GenerativeAI.Gemini.Enums;
using GenerativeAI.Gemini.Models.Part;

namespace GenerativeAI.Gemini.Models
{
    /// <summary>
    /// Represents a content part in the Gemini API, defining both the role (origin) and the content parts themselves.
    /// This class encapsulates a collection of <see cref="IPart"/> instances, which make up the actual content,
    /// and a <see cref="ContentRole"/> indicating whether the content was provided by the user or generated by the model.
    /// </summary>
    /// <param name="Parts">The collection of content parts.</param>
    /// <param name="Role">The role indicating whether the content is from the user or the model.</param>
    internal sealed record Content(ICollection<IPart> Parts, ContentRole Role);
}
