using GenerativeAI.Gemini.Models;

namespace GenerativeAI.Gemini
{
    /// <summary>
    /// Defines the contract for a Gemini prompt response data part.
    /// </summary>
    public interface IGeminiResponseData
    {
        /// <summary>
        /// Gets the collection of candidate responses generated by the model for this prompt.
        /// </summary>
        internal IEnumerable<Candidate> Candidates { get; }

        /// <summary>
        /// Gets the token usage statistics for this response.
        /// </summary>
        public GeminiUsageMetadata UsageMetadata { get; }

        /// <summary>
        /// Gets the version of the Gemini model that generated this response.
        /// </summary>
        public string ModelVersion { get; }

        /// <summary>
        /// Gets the unique identifier for this response.
        /// </summary>
        public string ResponseId { get; }
    }
}
