using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace GenerativeAI.Gemini.Enums
{
    /// <summary>
    /// Defines the role of the entity that generated the Gemini content.
    /// Used to distinguish between content provided by the user and content generated by the model.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ContentRole
    {
        /// <summary>
        /// Indicates that the content was provided by the user.
        /// </summary>
        User,

        /// <summary>
        /// Indicates that the content was generated by the Gemini AI model.
        /// </summary>
        Model
    }
}
