namespace GenerativeAI.Gemini.Enums
{
    /// <summary>
    /// Defines the type of a field in a structured Gemini prompt schema.
    /// This enum is used to specify the data type for each property in the structured prompt.
    /// </summary>
    public enum GeminiSchemaFieldType
    {
        /// <summary>
        /// The field type is automatically determined or not explicitly specified.
        /// </summary>
        AutoGenerated = 0,

        /// <summary>
        /// The field is a string value.
        /// </summary>
        String,

        /// <summary>
        /// The field is an integer value.
        /// </summary>
        Integer,

        /// <summary>
        /// The field is a numeric value (floating-point or decimal).
        /// </summary>
        Number,

        /// <summary>
        /// The field is a boolean value.
        /// </summary>
        Boolean,

        /// <summary>
        /// The field is an object containing nested properties.
        /// </summary>
        Object,

        /// <summary>
        /// The field is an array of values.
        /// </summary>
        Array,

        /// <summary>
        /// The field is an enumeration of predefined values.
        /// </summary>
        Enum
    }
}
